# Generated by Django 4.0.6 on 2023-01-08 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
    ]
