# Generated by Django 4.1.3 on 2023-02-22 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_created_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',)},
        ),
    ]
